# Generated by Django 3.0.8 on 2020-07-20 13:13

from django.db import migrations
from api.user.models import CustomUser


class Migration(migrations.Migration):
    def seed_data(apps, shema_editor):
        user = CustomUser(name="cyrille",
                          email="cyrisenahoun@gmail.com",
                          is_staff=True,
                          is_superuser=True,
                          )
        user.set_password("Tchami09")
        user.save()

    dependencies = [

    ]

    operations = [
        migrations.RunPython(seed_data)
    ]
